#!/usr/bin/env python
VERSION = "2.0"
import cgi
import cgitb
import string
import json
cgitb.enable()

print("Content-Type: text/html")
print()
print("<html><body>")

#Big important data sets go here.
days = ('Monday','Tuesday','Wednesday','Thursday','Friday') #For ordering purposes
times = {8:[],9:[],10:[],11:[],12:[],13:[],14:[],15:[],16:[],17:[],18:[]}

try:
	with open('timetable.json') as f:
		tt = json.load(f)
except FileNotFoundError:
	tt = {'Monday':times,'Tuesday':times,'Wednesday':times,'Thursday':times,'Friday':times,'users':[]}


def clearname(name):
	'''Removes a name from the timetable'''
	for d in days:
		for h in range(8,19):
			if name in tt[d][h]:
				tt[d][h].remove(name)
	if name in tt[users]:
		tt[users].remove(name)
			
def checks():
	'''Check that CAPTCHA is correct and inputs are safe.'''
	for i in name:
		if i not in string.letters:
			return False
	if captcha != 'apple':
		return False
	else:
		return True

def processform(): #This collects the data from the form (add.html)
	form = cgi.FieldStorage()
	name = str(form.getvalue('name'))
	captcha = str(form.getvalue('captcha'))
	
	if checks():
		clearname(name)
		
		for d in days:
			for h in range(8,19):
				if str(d + str(h)) in form:
					tt[d][h].append(name)
		
		tt[users].append(name)
	else:
		print('Sorry, something bad happened. Check that you answered the spambot question and that your name contains only letters, and try again.')


def generate(): #Builds the timetable for all users.
	s = str()
	s +=  'Currently tracking ' + str(len(tt[users])) + ' people\'s avaliability between classes.\n\n'
	s +=  '<table border=1>\n<tr><td></td><td>Monday</td><td>Tuesday</td><td>Wednesday</td><td>Thursday</td><td>Friday</td>\n'
	
	for h in range(8,19):
		s +=  "<tr><td>" + str(h) + '</td>'
		for d in days:
			s += '<td>'
			for i in tt[d][h]:
				s += i + '<br />'
			s += '</td>'
		s += '</tr>\n'

	s +=  '<br><br>Generated by TITP Version ' + VERSION
	index = open('index.txt','w')
	index.write(s)
	index.close()

def save():
	with open('timetable.json','w') as f:
		json.dump(tt,f)
		
if __name__ == '__main__':
	processform()
	generate()
	save()
	print('Data stored. Probably.')
