#!/usr/bin/env python3
import titp
import cgi
import cgitb
cgitb.enable()
import string
def checks(name, captcha):
	'''Check that CAPTCHA is correct and inputs are safe.'''
	for i in name:
		if i not in string.ascii_letters:
			return False
	if captcha != 'apple':
		return False
	else:
		return True

def processform(): 
	'''This collects the data from the form (add.html)'''
	form = cgi.FieldStorage()
	now = form.getvalue('now')
	if now is not None:
		titp.freenow(now)
	else:
		if form:
			name = str(form.getvalue('name'))
			captcha = str(form.getvalue('captcha'))
			
			if checks(name, captcha):
				titp.clearname(name)
				
				for d in titp.days:
					for h in titp.times:
						if form.getvalue(d + h):
							titp.tt[d][h].append(name)

				titp.tt['users'].append(name)
			else:
				print('Sorry, something bad happened. Check that you answered the spambot question and that your name contains only letters, and try again.')
def generate(): 
	'''Builds the timetable html for all users.'''
	s = str()
	s +=  '<p><a href="add.html">Add or modify availability</a></p>\n'
	s +=  '<p>Currently tracking ' + str(len(titp.tt['users'])) + ' people\'s availability between classes.</p>\n\n'
	s +=  '<div style="padding:1em"><table style="width:100%" border="1">\n<tr><td></td><td>Monday</td><td>Tuesday</td><td>Wednesday</td><td>Thursday</td><td>Friday</td></tr>\n'
	
	for h in titp.times:
		s +=  "<tr><td>" + str(h) + '</td>'
		for d in titp.days:
			s += '<td>'
			for i in titp.tt[d][h]:
				s += i + '<br />'
			s += '</td>'
		s += '</tr>\n'
	
	s +=  '<form method="post" action="titp.py"><p>Hello! My name is <input type="text" name="name" /> and I am free <input type="submit" value="right now!" /></p></form>'
	s +=  '</table></div>\n<p>Generated by TITP Version ' + titp.VERSION + '</p>'
	
	
	with open('page.html') as f:
		page = f.read()
	
	print(page.replace('<!--timetable-->',s))

if __name__ == '__main__':
	
	print('Content-Type: text/html')
	print('')

	
	processform()
	generate()
	titp.save()

